### ISSUE TITLE
Should we change the shader compile.bat?

### ISSUE THREAD

**Issue by RafaelFreita** [gabriellanzer/Ravine#10]
We saw that Sasha uses the "glslangValidator.exe" directly instead of shipping with the repo?

Maybe we should do that to?

**Comment by gabriellanzer** [comment]
Sure thing, we should! I guess compiler errors will happen in a near future if we keep to the same version of the .sprv compiler. Another option is to keep updating the compiler binaries.

**Comment by gabriellanzer** [comment]
Changed from compiler binaries to Google's ShaderC library runtime compilation. 💃
